---
- name: Install andrewrothstein.bash
  ansible.builtin.include_role:
    name: andrewrothstein.bash
- name: Install andrewrothstein.temurin
  ansible.builtin.include_role:
    name: andrewrothstein.temurin
  vars:
    openjdk_app: jre
- name: Checking for jython install in {{ jython_exe }}
  become_user: root
  become: true
  ansible.builtin.stat:
    path: '{{ jython_exe }}'
  register: jython_binary
- name: Downloading and installing jython
  when: not jython_binary.stat.exists
  block:
    - name: Downloading jython installer...
      become_user: root
      become: true
      ansible.builtin.get_url:
        url: '{{ jython_installer_url }}'
        dest: '{{ jython_tmp_installer_jar }}'
        mode: '644'
    - name: Installing jython...
      become_user: root
      become: true
      ansible.builtin.command: bash -lc 'java -jar "{{ jython_tmp_installer_jar }}" -s -d "{{ jython_install_dir }}"'
      args:
        creates: '{{ jython_exe }}'
      changed_when: false
    - name: Seeding jython...
      ansible.builtin.command: bash -lc "{{ jython_exe }} -c 'exit()'"
      changed_when: false
  always:
    - name: Rm -f {{ jython_tmp_installer_jar }}
      become_user: root
      become: true
      ansible.builtin.file:
        path: '{{ jython_tmp_installer_jar }}'
        state: absent
- name: Linking {{ jython_link }} to {{ jython_exe }}
  become_user: root
  become: true
  ansible.builtin.file:
    src: '{{ jython_exe }}'
    dest: '{{ jython_link }}'
    state: link
